[package]
name = "test_md3_standalone"
version = "0.1.0"
edition = "2021"


[dependencies]
wgpu = "0.20"
winit = "0.30"
bytemuck = { version = "1.14", features = ["derive"] }
pollster = "0.3"
glam = "0.24"
image = "0.24"

